services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - capybara
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcendence"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - capybara
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - 8443:443
    develop:
      watch:
        - path: ./nginx/nginx.conf
          action: rebuild

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - capybara
    restart: unless-stopped
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.ts
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  backend:
    container_name: backend
    build: ./backend
    networks:
      - capybara
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://transcendence:transcendence@db:5432/transcendence
    volumes:
      - ./uploads:/app/uploads
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
          ignore:
            - uploads/

networks:
  capybara:
    driver: bridge

volumes:
  postgres_data:
