services:
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - capybara
    depends_on:
      - frontend
      - backend
    ports:
      - 8443:443
    develop:
      watch:
        - path: ./nginx/nginx.conf
          action: rebuild

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production
    networks:
      - capybara

  backend:
    container_name: backend
    build: ./backend
    networks:
      - capybara
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: file:/data/dev.db
    volumes:
      - ./data:/data
      - ./uploads:/app/uploads

networks:
  capybara:
    driver: bridge
