import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/context/authContext";
import { SocketProvider } from "@/context/socket-context";
<<<<<<< HEAD
import { GameProvider } from "@/context/game-context";
import { LanguageProvider } from "@/context/languageContext";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import GameInviteDialog from "@/components/game-invite-dialog";
import { ReconnectionManager } from "@/components/game/reconnection-manager";
import { NavigationGuard } from "@/components/game/navigation-guard";
=======
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner"
>>>>>>> 3b7dd28 (merge: merge main branch)

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
<<<<<<< HEAD
          <LanguageProvider>
            <Suspense fallback={null}>
              <AuthProvider>
                <GameProvider>
                  <SocketProvider>
                    <Toaster position="top-center" />
                    <NavigationGuard />
                    <Suspense fallback={null}>
                      <Header />
                    </Suspense>
                    <GameInviteDialog />
                    <ReconnectionManager />
                    <main className="min-h-screen w-full">{children}</main>
                    <Suspense fallback={null}>
                      <Footer />
                    </Suspense>
                  </SocketProvider>
                </GameProvider>
              </AuthProvider>
            </Suspense>
          </LanguageProvider>
=======
          <AuthProvider>
            <SocketProvider>
              <Toaster position="top-center"/>
              <Header />
              <main className="min-h-screen w-screen">{children}</main>
              <Footer />
            </SocketProvider>
          </AuthProvider>
>>>>>>> 3b7dd28 (merge: merge main branch)
        </ThemeProvider>
      </body>
    </html>
  );
}
