// Temporary page to enable 2FA (generated by ChatGPT)
"use client";

import { useState } from "react";
import axios from "axios";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import Image from "next/image";

export default function TwoFASetupPage() {
  const [loading, setLoading] = useState(false);
  const [qrImage, setQrImage] = useState(null);
  const [backupCodes, setBackupCodes] = useState([]);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  const handleEnable2FA = async () => {
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const response = await axios.get("/api/me/2fa/enable");

      setQrImage(response.data.imageUrl);
      setBackupCodes(response.data.backupCodes);
      setSuccess(true);
    } catch (err: any) {
      console.error("Enable 2FA error:", err);
      setError(err.response?.data?.error || "An error occurred.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="grid h-screen place-items-center">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle className="text-center text-lg font-semibold">
            Two-Factor Authentication Setup
          </CardTitle>
        </CardHeader>
        <CardContent>
          {!qrImage ? (
            <div className="flex flex-col items-center">
              <Button onClick={handleEnable2FA} disabled={loading}>
                {loading ? "Enabling..." : "Enable 2FA"}
              </Button>
              {error && (
                <p className="text-red-500 text-sm mt-3 text-center">{error}</p>
              )}
            </div>
          ) : (
            <div className="text-center">
              <p className="mb-2 text-gray-700">
                Scan this QR code with your authenticator app:
              </p>
              <Image
                src={qrImage}
                alt="2FA QR Code"
                className="mx-auto my-4 w-48 h-48"
              />

              <p className="font-semibold text-gray-700 mb-2">
                Backup Codes (save these somewhere safe):
              </p>
              <div className="bg-gray-100 border rounded p-3 text-sm text-gray-800 text-left">
                <ul className="list-disc list-inside">
                  {backupCodes.map((code, i) => (
                    <li key={i}>{code}</li>
                  ))}
                </ul>
              </div>

              {success && (
                <p className="text-green-600 mt-3 font-medium">
                  ✅ 2FA enabled successfully!
                </p>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
